INSERT INTO products (name, description, price)
VALUES ('Smartphone Pro Max', 'Latest flagship smartphone with 128GB storage', 1299.99),
       ('Wireless Headphones', 'Noise-cancelling bluetooth headphones', 249.90),
       ('Gaming Laptop', 'High-performance laptop for gaming and productivity', 1899.00),
       ('Coffee Maker', 'Automatic drip coffee maker with timer', 89.95),
       ('Running Shoes', 'Professional running shoes with air cushioning', 159.99),
       ('Desk Lamp', 'LED desk lamp with adjustable brightness', 45.50),
       ('Backpack', 'Waterproof hiking backpack 40L capacity', 125.00),
       ('Bluetooth Speaker', 'Portable speaker with 12-hour battery life', 79.99),
       ('Fitness Tracker', 'Smart fitness watch with heart rate monitor', 199.00),
       ('Electric Kettle', 'Stainless steel electric kettle 1.7L', 34.99),
       ('Yoga Mat', 'Non-slip exercise mat for yoga and pilates', 29.95),
       ('Tablet 10 inch', 'Android tablet with stylus support', 349.00),
       ('Office Chair', 'Ergonomic office chair with lumbar support', 299.99),
       ('Air Fryer', 'Digital air fryer 5.8L capacity oil-free cooking', 149.90),
       ('Power Bank', 'Portable charger 20000mAh fast charging', 49.99),
       ('Book Light', 'Rechargeable LED reading light clip-on', 19.95),
       ('Water Filter', 'Advanced water filtration pitcher 10-cup', 39.99),
       ('Mouse Pad', 'Gaming mouse pad with RGB lighting', 24.99),
       ('Travel Mug', 'Insulated travel mug keeps drinks hot 8 hours', 27.50),
       ('Desk Organizer', 'Bamboo desk organizer with multiple compartments', 32.00);